#PBS -N speedy09
#PBS -e /dev/null
#PBS -o /dev/null
#PBS -l mem=5gb
#PBS -m ae
#PBS -M matthew.betts@bioquant.uni-heidelberg.de
dn_out=/net/netfile2/ag-russell/mechismo/jobs/
dn_fist=$GH/work/fist/trunk/Fist/
perl -I${dn_fist}lib ${dn_fist}script/fist_search.pl --outdir $dn_out --id pdb_phos.mods --stringency low < ${dn_fist}root/static/data/examples/pdb_phos.mods.txt 1> ${dn_out}pdb_phos.mods.out 2> ${dn_out}pdb_phos.mods.err

