#PBS -N speedy26
#PBS -e /dev/null
#PBS -o /dev/null
#PBS -l mem=20gb
#PBS -m ae
#PBS -M matthew.betts@bioquant.uni-heidelberg.de
dn_out=/net/netfile2/ag-russell/mechismo/jobs/
dn_fist=$GH/work/fist/trunk/Fist/
perl -I${dn_fist}lib ${dn_fist}script/fist_search.pl --outdir $dn_out --id phosphosites.background.9606 --stringency low < ${dn_fist}root/static/data/examples/phosphosites.background.9606.txt 1> ${dn_out}phosphosites.background.9606.out 2> ${dn_out}phosphosites.background.9606.err

