#PBS -N uniprot_dis_high
#PBS -e /dev/null
#PBS -o /dev/null
#PBS -l cput=04:59:59
#PBS -l mem=5gb
#PBS -m ae
#PBS -M matthew.betts@bioquant.uni-heidelberg.de
dn_out=/net/netfile2/ag-russell/mechismo/jobs/
dn_fist=$GH/work/fist/trunk/Fist/
perl -I${dn_fist}lib ${dn_fist}script/fist_search.pl --outdir $dn_out --id uniprot_disease_mods.high --stringency high < ${dn_fist}root/static/data/examples/uniprot_disease_mods.txt 1> ${dn_out}uniprot_disease_mods.high.out 2> ${dn_out}uniprot_disease_mods.high.err

